name: Update README

on:
  schedule:
    - cron: "0 * * * *" # Update every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Activity
        uses: actions-js/github-activity-readme@v1.0.3
        with:
          COMMIT_MSG: "Update README with recent activity"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contributions
        run: |
          echo "## 📅 Monthly Contributions" > contributions.md
          curl -s "https://api.github.com/users/konboot/events" | \
          jq '.[] | select(.type == "PushEvent") | .created_at' | \
          awk -F- '{print $1"-"$2}' | sort | uniq -c | sort -r >> contributions.md

      - name: Update README
        run: |
          sed -i '/## 📅 Monthly Contributions/,+10 d' README.md
          cat contributions.md >> README.md

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Monthly Contribution Summary"
